OHRI-1375: Medications, Labs & Appointment Summary removed from HIV Care and Treatment
UCSF-IGHS/openmrs-esm-ohri pull request #1476
Opened 2023-05-31 11:48 UTC by lucyjemutai

OHRI-1375: I did not completely remove the Medications, Labs & Appointment Summary removed from HIV Care and Treatment. Only hidden on the UI

2023-05-31 13:22 UTC, ODORA0 submitted a review, later dismissed

2023-05-31 14:35 UTC, pirupius requested changes

2023-05-31 14:35 UTC, pirupius commented on packages/esm-hiv-app/src/index.ts
> +        offline: false,
U need to comment out the whole block

2023-06-01 08:06 UTC, lucyjemutai commented on packages/esm-hiv-app/src/index.ts
> +        offline: false,
Okay

2023-06-06 11:56 UTC, pirupius approved these changes

2023-06-06 11:56 UTC, merged