OHRI 1419: Renamed Programs to Programmes
UCSF-IGHS/openmrs-esm-ohri pull request #1494
Opened 2023-06-13 13:30 UTC by arodidev

2023-06-13 13:49 UTC, ODORA0 commented
@arodidev Add screenshots of the change too

2023-06-13 14:08 UTC, arodidev commented
> 

@ODORA0 Screenshot added

2023-06-13 15:29 UTC, pirupius requested changes

2023-06-13 16:17 UTC, arodidev commented on packages/esm-ohri-core-app/src/ohri-dashboard/side-menu/ohri-dashboard-side-nav.component.tsx
> +        <p className={styles.sideNavTextHeader}>{t('programmes', 'Programmes')}</p>
@pirupius Well understood. So would this approach be better?

`<p className={styles.sideNavTextHeader}>{t('programs', 'Programmes')}</p>`

2023-06-14 09:23 UTC, closed without merging

2023-06-14 09:24 UTC, pirupius commented
@arodidev why did u close this PR?