OHRI-1606: Remove Timeline and Previous pregnancies from the mother's MNCH Summary
UCSF-IGHS/openmrs-esm-ohri pull request #1558
Opened 2023-07-07 13:21 UTC by lucyjemutai

Remove Timeline and Previous pregnancies from the mother's MNCH Summary

2023-07-07 13:26 UTC, lucyjemutai commented
I have not deleted the timeline and previous pregnancies components

2023-07-10 06:29 UTC, pirupius requested changes

2023-07-10 06:29 UTC, pirupius commented on packages/esm-ohri-pmtct-app/src/views/mch-summary/mch-summary.component.tsx
> -                </TabPanel>
Please delete the unused components

2023-07-10 09:29 UTC, lucyjemutai commented on packages/esm-ohri-pmtct-app/src/views/mch-summary/mch-summary.component.tsx
> -                </TabPanel>
Done

2023-07-10 09:41 UTC, pirupius approved these changes

2023-07-10 09:42 UTC, merged