OHRI-1513: Total number of HIV Exposed Children Enrolled in Follow Up…
UCSF-IGHS/openmrs-esm-ohri pull request #1623
Opened 2023-08-18 13:36 UTC by lucyjemutai

… Care updated on the children tile

- Total number of children born to HIV positive mothers and registered in mother-baby follow-up care meaning they had their first infant postnatal care visit.

![image](https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/130601439/0338c8a8-a37b-4ede-bc2a-c0792874c803)

2023-08-18 14:31 UTC, Herobiam approved these changes

2023-08-21 05:32 UTC, ODORA0 approved these changes
LGTM

2023-08-21 05:33 UTC, ODORA0 requested changes
@lucyjemutai Please take care of the merge conflicts

2023-08-21 06:19 UTC, lucyjemutai commented
I have addressed the merge conflicts

2023-08-21 14:04 UTC, ODORA0 submitted a review, later dismissed

2023-08-22 09:59 UTC, closed without merging