OHRI-2053 CaCx - update metadata to use config instead of constants
UCSF-IGHS/openmrs-esm-ohri pull request #1736
Opened 2024-01-09 09:45 UTC by arodidev

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Summary

Refactor esm-cervical-cancer-app to use values from config instead of constants

## Screenshots

## Related Issue

## Other

2024-01-10 10:43 UTC, ODORA0 requested changes
@arodidev Let us also add configuration for the form names, just add a new node formNames and do the same for all references of the forms in the components. See example [here](https://github.com/UCSF-IGHS/openmrs-esm-ohri/pull/1735/files#diff-4971ea2a41aa5251ce5565f4ba32d5c44eda061777f5e4b3471686a51063fed1R85)

2024-01-11 07:27 UTC, pirupius requested changes
Some final tweaks before we can get this in

2024-01-11 07:27 UTC, pirupius commented on packages/esm-cervical-cancer-app/src/constants.ts
> -//cacx registration
Please delete this file if it's empty

2024-01-11 07:27 UTC, pirupius commented on packages/esm-cervical-cancer-app/src/config-schema.ts
> +  obsConcepts: Object;
add `formNames`

2024-01-11 07:32 UTC, pirupius approved these changes

2024-01-11 07:38 UTC, ODORA0 approved these changes

2024-01-11 07:38 UTC, merged