OHRI-2118-added the visits tables under tpt patient summary
UCSF-IGHS/openmrs-esm-ohri pull request #1795
Opened 2024-01-31 11:57 UTC by kirwea

added the visits tables under tpt patient summary

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

![screenshot_2024-01-31_at_14 53 38_720](https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/117803438/46fbb11b-0238-4b84-b8c7-da24d0b2e4a5)
 

## Related Issue

## Other

2024-01-31 15:51 UTC, arodidev commented
@kirwea kindly add a more recent screenshot representing your work, thanks.

2024-02-01 08:18 UTC, pirupius requested changes

2024-02-01 08:18 UTC, pirupius commented on packages/esm-tb-app/src/views/tpt/patient-summary/patient-summary.component.tsx
> +    [],
Please talk to Veronica about requirements for this

2024-02-06 06:38 UTC, pirupius commented
Not need for this anymore

2024-02-06 06:38 UTC, closed without merging