Translations added successfully for these three languages : Amheric ,French, Khmer
UCSF-IGHS/openmrs-esm-ohri pull request #1888
Opened 2024-07-01 07:53 UTC by Art-Ndiema

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes the ticket number in the format `OHRI-123 My PR title`.
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

<img width="1581" alt="Screenshot 2024-07-01 at 10 47 22 AM" src="https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/106247754/42293db6-f13e-4856-9aab-ae42a5c15788">
<img width="1232" alt="Screenshot 2024-07-01 at 10 48 21 AM" src="https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/106247754/6bb1e7c1-0388-4923-9726-3942cdb5fcae">
<img width="1243" alt="Screenshot 2024-07-01 at 10 52 38 AM" src="https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/106247754/4c5c9d22-6a9d-401f-96ee-c7eb16261f04">

## Related Issue

## Other

2024-07-01 08:08 UTC, CynthiaKamau reviewed
Thanks @Art-Ndiema , please undo the changes on the package.json and yarn.lock file since we use next `openmrs` version

2024-07-01 14:53 UTC, CynthiaKamau approved these changes

2024-07-02 06:42 UTC, hadijahkyampeire requested changes
Thanks @Art-Ndiema but I think you missed translating some values

2024-07-02 06:42 UTC, hadijahkyampeire commented on packages/esm-cervical-cancer-app/translations/km.json
> +  "cacxSummary": "CaCx Summary"
```suggestion
  "cacxSummary": "CaCx Summary"
  "cacxSummary": "cacx សង្ខេប
```

2024-07-02 06:42 UTC, hadijahkyampeire commented on packages/esm-cervical-cancer-app/translations/fr.json
> +  "cacxSummary": "CaCx Summary"
```suggestion
  "cacxSummary": "CaCx Summary"
  "cacxSummary": "Résumé du cacx"
```

2024-07-02 06:42 UTC, hadijahkyampeire commented on packages/esm-cervical-cancer-app/translations/am.json
> +  "cacxSummary": "CaCx Summary"
```suggestion
  "cacxSummary": "CaCx Summary"
  "cacxSummary": "cacx ማጠቃለያ
"
```

2024-07-02 06:42 UTC, hadijahkyampeire commented on packages/esm-ohri-core-app/translations/km.json
> +  "programmes": "Programmes"
```suggestion
  "programmes": "Programmes"
  "programmes": "កម្មវិធី"
```

2024-07-02 06:42 UTC, hadijahkyampeire commented on packages/esm-ohri-core-app/translations/am.json
> +  "programmes": "Programmes"
```suggestion
  "programmes": "Programmes"
  "programmes": "ፕሮግራሞች"
```

2024-07-02 06:42 UTC, hadijahkyampeire commented on packages/esm-tb-app/translations/fr.json
> +  "activeDrCases": "Active DR Cases",
Lets translate these, for example the first value should be `Cas de reprise après sinistre actifs`

2024-07-02 22:15 UTC, hadijahkyampeire reviewed
Just minor cleanups

2024-07-02 22:15 UTC, hadijahkyampeire commented on packages/esm-cervical-cancer-app/translations/am.json
> +  "cacxSummary": "CaCx Summary"
You don't need these other English translations, all you need is the same key.

2024-07-02 22:15 UTC, hadijahkyampeire commented on packages/esm-cervical-cancer-app/translations/fr.json
> +  "cacxSummary": "CaCx Summary"
ditto

2024-07-02 22:15 UTC, hadijahkyampeire commented on packages/esm-cervical-cancer-app/translations/km.json
> +  "cacxSummary": "CaCx Summary"
ditto

2024-07-03 06:08 UTC, GKMuthee commented
@hadijahkyampeire @Art-Ndiema has Amharic been implemented on this PR? 
Regarding your question on other languages: Portuguese and Swahili.
cc: @eudson @ebambo

2024-07-03 06:50 UTC, hadijahkyampeire commented
Thanks @GKMuthee , Amharic is already added, @Art-Ndiema will add Swahili and Portuguese

2024-07-04 08:28 UTC, hadijahkyampeire approved these changes
Thanks @Art-Ndiema , let's merge this

2024-07-04 08:28 UTC, merged