OHRI-156 tooltip support for questions
UCSF-IGHS/openmrs-esm-ohri pull request #639
Opened 2021-11-25 10:10 UTC by pirupius

2021-11-26 03:07 UTC, ebambo requested changes
@pirupius can you abstract this code:
```
if (data.results.length) {
         const concept = data.results[data.results.length - 1];
         setConceptName(`Concept Name: ${concept.display} \n UUID: ${concept.uuid}`);
  }
```
It is repeated in all field types components

2021-11-29 14:20 UTC, ebambo requested changes
Please see my comments

2021-12-01 14:03 UTC, pirupius commented
@ebambo changes have been pushed

2021-12-02 07:56 UTC, ebambo approved these changes

2021-12-02 07:56 UTC, merged